KiCad စာရွက်စာတမ်းများ
===================

ဤ repository တွင် တရားဝင် link:http://www.kicad-pcb.org/[KiCad] စာရွက်စာတမ်းများ ပါဝင်ပါသည်။

image:http://ci.kicad-pcb.org/buildStatus/icon?job=any-kicad-doc-head["Build Status",
link="http://ci.kicad-pcb.org/job/any-kicad-doc-head/"]
image:https://img.shields.io/badge/docs-stable-brightgreen.svg["Stable version docs",
link="http://docs.kicad-pcb.org/"]
image:https://img.shields.io/badge/docs-nightly-lightgrey.svg["Nightly docs",
link="http://ci.kicad-pcb.org/job/any-kicad-doc-head/lastSuccessfulBuild/artifact/src/"]

== ပါဝင်ကူညီခြင်း (Contributing)

စာရွက်စာတမ်းနှင့် ၎င်း၏ ဘာသာပြန်ချက်များအကြောင်းကို link:https://github.com/KiCad/kicad-doc/issues[repository issues] တွင် ဆွေးနွေးနိုင်ပါသည်။

ဘာသာပြန်ဆိုမှု လုပ်ငန်းစဉ်တွင် ပါဝင်လိုပါက link:translation_instructions.adoc[] ကို ဖတ်ရှုပါ။ +
သင်၏ ဘာသာပြန် pull request များကို master branch သို့ တင်သွင်းပေးပါ။ +
docs versioning အကြောင်း အသေးစိတ်ကို link:docs-versioning.adoc[] တွင် ကြည့်ရှုပါ။

link:https://github.com/KiCad/kicad-doc/fork[pull-request တင်သွင်းခြင်း] မပြုမီ အပြောင်းအလဲများကို မည်သို့ စမ်းသပ်ရမည်ကို အောက်ပါညွှန်ကြားချက်များတွင် ရှင်းပြထားပါသည်။

== လိုအပ်ချက်များ (Dependencies)

* http://asciidoc.org/[AsciiDoc] >= 8.6.9 သည် စာရွက်စာတမ်း၏ ဘာသာစကားဖြစ်သည့်အပြင် PDF နှင့် HTML output များကို ထုတ်လုပ်ရန် အသုံးပြုသည့် tool လည်း ဖြစ်ပါသည်။

dblatex သို့မဟုတ် docbook ကဲ့သို့သော အခြား external tool သို့မဟုတ် intermediate format တစ်ခုမျှ မလိုအပ်ဘဲ PDF နှင့် epub စာရွက်စာတမ်း format များကို တိုက်ရိုက် ထုတ်လုပ်နိုင်စွမ်း ရှိသဖြင့်၊ http://asciidoctor.org/[asciidoctor] tool များ လုံလောက်စွာ တည်ငြိမ်လာသောအခါ နောင်တွင် ၎င်းသို့ ပြောင်းလဲအသုံးပြုနိုင်ဖွယ် ရှိပါသည်။ http://asciidoctor.org/docs/convert-asciidoc-to-pdf/[asciidoctor-pdf] project ကို ကြည့်ရှုပါ။

* https://po4a.alioth.debian.org/[po4a] >= 0.45 ကို compilation အဆင့် နောက်ဆုံးမတိုင်မီ၊ အင်္ဂလိပ်ဘာသာဖြင့် ရေးသားထားသော AsciiDoc စာရွက်စာတမ်းများကို အခြားဘာသာစကားများသို့ ဘာသာပြန်ရန် အသုံးပြုပါသည်။
* CMake >= 2.8
* dblatex >= 0.3.4
* gettext >= 0.18
* source-highlight
* ဂျပန်ဘာသာ PDF များ build လုပ်သည့်အခါ _VL Gothic_ font လိုအပ်ပါသည်။ `fonts-vlgothic` ဟု အမည်ပေးထားသည့် package ကို ရှာဖွေပါ။ သို့မဟုတ်ပါက build error များကို ရှောင်ရှားရန် **LANGUAGES** option ကို အသုံးပြုပါ။
* ဆိုင်ရီလစ် (Cyrillic) စာလုံးများ (ရုရှားဘာသာကဲ့သို့) ပါဝင်သည့် PDF ဖိုင်များ build လုပ်ရန်အတွက် _freefont-ttf_ fonts package လိုအပ်ပါသည်။ ထို့ကြောင့် အလားတူအမည်ရှိသည့် package ကို ရှာဖွေရန် လိုအပ်ပါမည်။

=== Debian / Ubuntu

Debian / Ubuntu တွင် dependencies များကို install လုပ်ရန် အောက်ပါအတိုင်း run ပါ (space 1.5GiB ခန့် လိုအပ်ပါသည်)-

    sudo apt-get install asciidoc cmake dblatex fonts-freefont-ttf \
    fonts-vlgothic gettext git make po4a source-highlight \
    texlive-lang-cyrillic texlive-lang-english texlive-lang-european \
    texlive-lang-french texlive-lang-german texlive-lang-italian \
    texlive-lang-japanese texlive-lang-other texlive-lang-polish \
    texlive-lang-spanish texlive-xetex texlive-lang-chinese \
    libunicode-linebreak-perl

NOTE: Debian Jessie နှင့် Ubuntu 16.04 LTS တွင် texlive-lang-european package မရှိပါ၊ ၎င်းအစား texlive-lang-dutch package ကို install လုပ်ပါ။

NOTE: Ubuntu 14.04 LTS တွင် texlive-lang-japanese မရှိပါ။ ၎င်းအစား texlive-lang-cjk ကို install လုပ်ပါ။

သို့မဟုတ် space ပြဿနာ မရှိပါက-

    sudo apt-get install asciidoc cmake dblatex fonts-freefont-ttf \
    fonts-vlgothic gettext git make po4a source-highlight \
    texlive-lang-all texlive-xetex libunicode-linebreak-perl

=== Fedora

Fedora တွင် dependencies များကို install လုပ်ရန် အောက်ပါအတိုင်း run ပါ-

    sudo dnf install git make cmake asciidoc gettext po4a dblatex \
    source-highlight texlive vlgothic-fonts perl-Unicode-LineBreak \
    texlive-scheme-full texlive-collection-xetex gnu-free-serif-fonts \
    gnu-free-mono-fonts gnu-free-sans-fonts

=== Manjaro Linux

Manjaro တွင် dependencies များကို install လုပ်ရန် အောက်ပါအတိုင်း run ပါ-

	sudo  pacman -S asciidoc cmake dblatex ttf-freefont gettext \
	po4a source-highlight  texlive-langchinese texlive-langcyrillic \
	texlive-langjapanese texlive-langextra texlive-langkorean \
	texlive-langgreek perl-unicode-linebreak

NOTE: AUR package ဖြစ်သည်

	yaourt -S ttf-vlgothic

== စာရွက်စာတမ်းများ Build လုပ်ခြင်း (Building the docs)

=== Windows

link:windows_dependencies.adoc[] ဖြင့် စတင်ပြီး အောက်ပါအတိုင်း run ပါ-

    cd kicad-doc
    mkdir build
    cd build
    cmake -G "MinGW Makefiles" -DPDF_GENERATOR=FOP ../
    make

=== MacOS / Linux

    cd kicad-doc
    mkdir build
    cd build
    cmake ../
    make

=== Docker
Container တစ်ခုအတွင်း စာရွက်စာတမ်းကို build လုပ်လိုပါက link:utils/docker/README.adoc[] ကို ဖတ်ရှုပါ။

=== CMake Build Options (တည်ဆောက်မှု ရွေးချယ်စရာများ)

==== BUILD_FORMATS

ပုံမှန်အားဖြင့် **BUILD_FORMATS** ကို document format များအားလုံးကို build လုပ်နိုင်ရန် `"html;pdf;epub"` ဟု သတ်မှတ်ထားပါသည်။

format တစ်စိတ်တစ်ပိုင်းသာ build လုပ်လိုပါက **BUILD_FORMATS** ကို သတ်မှတ်နိုင်ပါသည်၊ ဥပမာ- `-DBUILD_FORMATS=html`

format တစ်ခုတည်းကိုသာ enable ထားပါက package အမည်တွင် ထို format ပါဝင်အောင် ပြောင်းလဲပေးပါသည်။

==== LANGUAGES

ပုံမှန်အားဖြင့် CMake သည် စာရွက်စာတမ်းတစ်ခုစီအတွက် ရရှိနိုင်သော ဘာသာစကားအားလုံးကို build လုပ်ရန် configure လုပ်ပါသည်။

CMake ဖြင့် build ပြုလုပ်စဉ် **LANGUAGES** option ကို အသုံးပြုခြင်းဖြင့် ဘာသာစကား တစ်ခု သို့မဟုတ် အချို့ကိုသာ build လုပ်နိုင်ပါသည်၊ ဥပမာ- `-DLANGUAGES="it;en;de"` စသည်ဖြင့်။

လက်ရှိတွင် ရရှိနိုင်သော ဘာသာစကားများမှာ `ca`, `de`, `en`, `es`, `fr`, `id`, `it`, `ja`, `pl`, `ru` နှင့် `zh` တို့ ဖြစ်ကြသော်လည်း၊ ဘာသာစကား code မည်သည်ကိုမဆို ရွေးချယ်နိုင်ပါသည်။ ဘာသာပြန်ပြီးသား စာရွက်စာတမ်းများသာ build လုပ်မည်ဖြစ်၍ ဘာသာစကားအချို့အတွက် စာရွက်စာတမ်း တစ်စိတ်တစ်ပိုင်းသာ ထွက်ရှိနိုင်ပါသည်။

==== SINGLE_LANGUAGE

ဤ option သည် deprecated ဖြစ်ပြီး ၎င်းအစား **LANGUAGES** ကို အသုံးပြုပါ

==== PDF_GENERATOR

ပုံမှန်အားဖြင့် CMake သည် PDF များ build လုပ်ရန် dblatex ကို အသုံးပြုပါသည်။

CMake build ကို configure လုပ်စဉ် **PDF_GENERATOR** option ကို အသုံးပြုခြင်းဖြင့် DBLATEX သို့မဟုတ် FOP ကို ရွေးချယ်၍ PDF များ build လုပ်နိုင်ပါသည်။

ဥပမာအားဖြင့်၊ PDF များ build လုပ်ရန် FOP ကို အသုံးပြုလိုပါက `-DPDF_GENERATOR=FOP` ဟု ရေးပါ။ **BUILD_FORMATS** option တွင် `pdf` ပါဝင်ခြင်း မရှိပါက **PDF_GENERATOR** option သည် build အပေါ် သက်ရောက်မှု ရှိမည် မဟုတ်ပါ။

ဤ option သည် build လုပ်ထားသော package အမည်ကို ပြောင်းလဲပေးမည် မဟုတ်ပါ။

=== စာရွက်စာတမ်းများကို Package ပြုလုပ်ခြင်း (Packaging the docs)
စာရွက်စာတမ်းများသည် အထက်တွင် ဖော်ပြခဲ့သည့်အတိုင်း CMake ကို အသုံးပြုသဖြင့်၊ packager တစ်ဦးအနေဖြင့် install ပြုလုပ်ရန် ပုံမှန် CMake နည်းလမ်းကို အသုံးပြုပါ၊ ဥပမာ-

    mkdir build; cd build
    cmake -DCMAKE_INSTALL_PREFIX=/usr ..
    make install

OS X တွင်ဖြစ်ပါက အောက်ပါကဲ့သို့ လိုချင်နိုင်ပါသည်-

    mkdir build; cd build
    cmake -DCMAKE_INSTALL_PREFIX="/Library/Application Support/kicad" ..
    make install
